shallow_clone: true


# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - packages -> **\packages.config


# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release
platform: Any CPU


before_build:
  - nuget restore
